seed: 42
data:
  datapath: "churner/ml/data/WA_Fn-UseC_-Telco-Customer-Churn.csv"
  label: "Churn"
  numerical:
    - "tenure"
    - "MonthlyCharges"
    - "TotalCharges"
  categorical:
    - "gender"
    - "SeniorCitizen"
    - "Partner"
    - "Dependents"
    - "PhoneService"
    - "MultipleLines"
    - "InternetService"
    - "OnlineSecurity"
    - "OnlineBackup"
    - "DeviceProtection"
    - "TechSupport"
    - "StreamingTV"
    - "StreamingMovies"
    - "Contract"
    - "PaperlessBilling"
    - "PaymentMethod"
model:
  savepath: "churner/app/models"
  k: 5
  name: "churner_model.pkl"
  test_set_percentage: 0.3
  calibration_set_percentage: 0.5
  n_trials: 10
inference:
  alert_threshold: 0.7
